services:

  postgres:
    image: postgres:17
    container_name: nativewit-postgres

    environment:
      POSTGRES_DB: nativewit_coupon_db
      POSTGRES_USER: nativewit
      POSTGRES_PASSWORD: nativewit123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nativewit -d nativewit_coupon_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: nativewit-coupon-app

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/nativewit_coupon_db
      DB_USERNAME: nativewit
      DB_PASSWORD: nativewit123

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: